### ISSUE TITLE
log4z 日志输入到其他日志文件

### ISSUE THREAD

**Issue by ganxunzou** [zsummer/log4z#26]
I have a applet. 
for(int i=0;i<10000;i++)
{
if(i%2==0)
{
  writelog("myaaa.log","aaaa");
}
else
{
  writelog("myaaa.log","aaaa");
}
}

**Comment by zsummer** [comment]
writelog?   Do you need any help?

**Comment by ganxunzou** [comment]
Will you Chinese?

**Comment by zsummer** [comment]
参考下advance_test.  可以把不同的日志输出到不同的文件,  不知道和你的需求是否一致.

**Comment by ganxunzou** [comment]
我测试发现可能是我采用多线程引起的。
