### ISSUE TITLE
Log4zFileHandler::readContent中fread可能失败

### ISSUE THREAD

**Issue by daviyang35** [zsummer/log4z#27]
if (fread(&content[0], 1, filelen, _file) != (size_t)filelen)
{
	content.clear();
	return content;
}

fread函数在读取filelen长度数据时，可能少于filelen
此时不一定是文件错误或者遇到文件尾
测试发现，使用rb模式打开文件时，fread返回的长度才等于文件长度
可能是因为r模式下，控制字符被转义了。

**Comment by zsummer** [comment]
fixed
