### ISSUE TITLE
两个建议

### ISSUE THREAD

**Issue by upperli** [zsummer/log4z#29]
1 .日志名字设置可调节
2.mac系统proc_name函数会对程序名进行15字节的截断，导致mac与linux运行结果不一致

**Comment by zsummer** [comment]
日志名字是可以改的.  
mac下的程序名截断我觉得问题不大, 15字节已经够长了 暂时先不考虑去解决.

**Comment by zsummer** [comment]
下午改热更新机制的代码, 顺手把主日志的名字也调整为可以改了,   日志的名字可改机制很早以前就加了, 但主日志的禁止更改名字判断一直没去掉.
