### ISSUE TITLE
请问rotate log怎么设置

### ISSUE THREAD

**Issue by lzx1413** [zsummer/log4z#38]
我想进行循环记录日志，节省空间，不知道应该怎么设置

**Comment by zsummer** [comment]
log4z支持日志分割滚动, 但不支持回滚或者自动清除老日志的功能.

如果你能接受不保留任何老日志的做法, 你可以直接修改log4z.cpp: LogerManager::openLogger 函数下文件名的生成规则,  把含有时间戳和进程号和滚动编号的部分删除,  然后在pLogger->_handle.open(path.c_str(), "ab"); 这行里把"ab"改成"w"就可以了.

如果你的需求是 自动清除一部分更旧的日志但保存部分较新的日志 可以考虑直接写个脚本自动清理.
可以尝试在log4z.cpp: LogerManager::openLogger 中 执行handler.open前写个匹配规则去删除老日志, 
https://github.com/zsummer/breeze/blob/cluster/source/common/utls.h 这个头文件的searchFiles是一个支持通配符的跨平台的文件搜索函数, removeFile是删除文件的函数,  不过集成起来可能也略微麻烦一些(要拆部分实现的依赖从utls.h种)
考虑到删除日志是存在较为严重风险的一个方法, 并且可能遇到权限问题, 所以并没有考虑支持日志回滚和自动按规则清除老日志的功能. (还出于尽量保持实现的简洁 和 有那么一点点点想偷懒(偷懒成分绝对不多))

**Comment by lzx1413** [comment]
好的，我明白了，谢谢
