### ISSUE TITLE
请问一下libproc.h找不着的问题

### ISSUE THREAD

**Issue by LoveULin** [zsummer/log4z#39]
![image](https://cloud.githubusercontent.com/assets/7943800/15647399/e03a0708-2695-11e6-8ed6-3d03ee484a88.png)
同事在ios上编译我把log4z.cpp整合进去的工程，具体编译环境我也不太清楚。。不过会报找不着libproc.h的错误；libproc.h上边的dispatch.h没问题能找着；请问libproc.h这个文件的路径对吗？？或者需要配置什么编译参数吗？？

**Comment by zsummer** [comment]
你注释掉试试呢? 
这个头文件的引入是因为要获取进程名 即proc_name这个接口的调用.  如果注释掉能编译通过最好 不能通过的话 把proc_name那行代码也一块注释掉或者写死就可以了.  注释掉proc_name的的效果是 日志的文件名缺少进程名信息. 其他的都无影响.
最近没有折腾过IOS, 先给你一个临时解决方案吧 希望有帮助.

**Comment by LoveULin** [comment]
注掉#include <libproc.h>可以用 非常感谢！！:D

**Comment by zsummer** [comment]
我查了下资料IOS下proc_name所在的头文件是sys/proc.h, 并且不存在libproc.h
但OSX下又只在libproc.h中有声明.
我提交了一个宏定义检测目标是否是TARGET IOS 然后根据具体环境include不同的头文件. 但没有ios环境可以测试当前,暂没有验证.
先mark下 以后再测.

**Comment by zsummer** [comment]
刚翻了下头文件, proc_name在OSX的sdk中以下位置存在声明
Frameworks/Kernel.framework/Headers/sys/proc.h
usr/include/libproc.h
但在iOS下并没有找到, 感觉很奇怪的样子.

**Comment by zsummer** [comment]
在google的开源项目Google APIs Client Library for C++中找到了同样的处理方式
https://github.com/google/google-api-cpp-client/blob/master/src/googleapis/client/util/program_path.cc
看起来也是判断IPHONE环境后就直接跳过了.

**Comment by LoveULin** [comment]
学习了！！非常感谢！！:D 不过注掉#include之后proc_name就不能用了。。之前说错了。。抱歉
看来是不是也是得像你说的google那个开源项目里一样 不是IPHONE环境才能用proc_name 然后IPHONE环境就走到else那里用Linux (default) version版本的实现？？

**Comment by zsummer** [comment]
睡觉前我想到那个问题了 实在太困了.   刚查了下 和你看到的一样,  /proc/pid/那个方式OSX是不支持的  难道IOS支持么?　如果是这样我也只能吐槽了. 也或许 else那里只是保证能编译通过 但并不能获得预期的结果.

**Comment by LoveULin** [comment]
嗯嗯哈哈有可能 我让同事帮忙在ios一个版本上先试试 要可以的话回头还得在多个版本上都试一把

**Comment by LoveULin** [comment]
这几天把这事给忘了。。在iphone上试了试确实就像你说的能编译通过 但是会返回",/"。。应该并不是预期的结果@_@

**Comment by zsummer** [comment]
嗯 那我也那样搞下好了 对日志命名来说 特别是客户端 那个前缀也没什么重要的.

**Comment by LoveULin** [comment]
好好lol

**Comment by zsummer** [comment]
吓
