### ISSUE TITLE
存在内存泄露问题

### ISSUE THREAD

**Issue by molixiaoge** [zsummer/log4z#40]
valgrind测试存在内存泄露，makeLogData 内存没有释放，测试代码如下:

1.   ILog4zManager::getRef().start();
2.   LOGD("stream input *** " <<1 );

**Comment by zsummer** [comment]
为了提高性能, 会缓存不高于200个被释放的LogData来复用, 相当于对象池.

**Comment by molixiaoge** [comment]
恩,看到了小于200的判断,但是main函数结束了,对象析构函数并未做delete处理...，虽然说程序都已经结束了。

**Comment by zsummer** [comment]
可以少写一部分代码.
