### ISSUE TITLE
why lock here ?

### ISSUE THREAD

**Issue by king09fish** [zsummer/log4z#42]
```
    std::string name;
    std::string path;
    _hotLock.lock();
    name = pLogger->_name;
    path = pLogger->_path;
    _hotLock.unLock();
```

why use lock here ? the value of name and path is not change

**Comment by zsummer** [comment]
_hotLock is  garbage code.    
at history version.   change the  name and path  need across more than one thread.   so need the lock.     
but new version change name and path via  thread safe log queue ,  don't need to do this.  
I will clean this code at the follow version .   
thanks .

**Comment by zsummer** [comment]
already clean
