### ISSUE TITLE
hello 

### ISSUE THREAD

**Issue by king09fish** [zsummer/log4z#43]
hello ,why code like this? i don't know your purpose？Can you say in detailed?

inline Log4zStream & Log4zStream::writeBinary(const Log4zBinary & t)
{
    writeData("%s", "\r\n\t[");
    for (int i = 0; i < t._len; i++)
    {
        if (i % 16 == 0)
        {
            writeData("%s", "\r\n\t");
            _this << (void_)(t._buf + i);
            writeData("%s", ": ");
        }
        writeData("%02x ", (unsigned char)t._buf[i]);
    }
    writeData("%s", "\r\n\t]\r\n\t");
    return *this;
}

**Comment by king09fish** [comment]
you can speak Chinese? i know Chinese a little

**Comment by zsummer** [comment]
it used to print printable character  and  hexadecimal.  some context of use like   print binary stream for  communication protocol.    
example log:   
```  
2016-07-07 13:39:45.017 LOG_DEBUG 
        [
        00007ffecb095700: 00 00 00 00 02 00 00 00 00 00 00 00 01 00 00 00 
        00007ffecb095700:  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  . 
        00007ffecb095710: 21 eb 7d 57 00 00 00 00 00 00 00 00 07 00 00 00 
        00007ffecb095710:  !  .  }  W  .  .  .  .  .  .  .  .  .  .  .  . 
        00007ffecb095720: 6e 65 77 6e 61 6d 65 
        00007ffecb095720:  n  e  w  n  a  m  e 
        ]
```

**Comment by zsummer** [comment]
我中国话说的非常溜的.
