### ISSUE TITLE
Log4z难道不支持MFC？

### ISSUE THREAD

**Issue by xudev** [zsummer/log4z#50]
我在但文档项目中，增加了log4z ，退出时就会有内存泄漏，而注释掉log4z就不会有泄漏了。

其中我什么日志都不写只调用ILog4zManager::getRef().start();就会有泄漏。

--------------------------------------------------------------------------------
Dumping objects ->
{367} normal block at 0x009D9440, 8224 bytes long.
 Data: <                > 00 00 00 00 00 00 00 00 00 00 00 00 05 00 00 00 
{362} normal block at 0x009D73E0, 8224 bytes long.
 Data: <                > 00 00 00 00 00 00 00 00 00 00 00 00 05 00 00 00 
Object dump complete.
--------------------------------------------------------------------------------
大小都是 8224，固定的。

麻烦大牛帮忙看看。。。。

**Comment by zsummer** [comment]
_freeLogDatas 这个对象池是整个进程生命周期驻留内存的, 如果你不想看到 就析构的时候释放一下. 进程周期的内存我一般不做回收处理.

**Comment by xudev** [comment]
感谢！已解决！
