### ISSUE TITLE
进程长时间不写（跨天），重新新建log文件写入的问题

### ISSUE THREAD

**Issue by fssqawj** [zsummer/log4z#54]
Great Project！！

使用默认参数，进程长时间不写log（跨天），再次写入时会重新新建一个log文件（文件名写入时间变化，pid不变）

确认不是log文件写满的问题~

是否有方法或参数设置跨天不重新新建log文件？

**Comment by zsummer** [comment]
这个是特性 保证对应时间的日志追加到对应日期名的日志文件中  如果不想重建 你找到生成文件名的代码行 把文件名序列化日期的部分删除掉就可以了.
