### ISSUE TITLE
android compile err.error: 'gcvt' was not declared in this scope.

### ISSUE THREAD

**Issue by cjaizhangyu** [zsummer/log4z#56]
anroid-ndk stdlib.h not surpport gcvt.

[armeabi] Compile++ thumb: log4z <= log4z.cpp
In file included from ./log4z.cpp:37:
./log4z.h:829:13: error: use of undeclared identifier 'gcvt'
            gcvt(t, isSimple ? 7 : 16, _cur);
            ^
./log4z.cpp:163:41: error: use of undeclared identifier 'POSIX_FADV_DONTNEED'
          posix_fadvise(fd, index, len, POSIX_FADV_DONTNEED);
                                        ^
./log4z.cpp:1254:49: error: use of undeclared identifier 'SYS_gettid'
        pLog->_threadID = (unsigned int)syscall(SYS_gettid);
                                                ^
3 errors generated.
make: *** [obj/local/armeabi/objs/log4z/log4z.o] Error 1

**Comment by cjaizhangyu** [comment]
自定义API 和宏(ANDROID) 判定。

**Comment by WeatheringHzl** [comment]
Hello, I have the same problem when I use android-ndk. Could you share the experience to solve the problem? Thank you!
